/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BankFacet,
  BankFacetInterface,
} from "../../../contracts/facets/BankFacet";

const _abi = [
  {
    inputs: [],
    name: "getRewardsBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50608580601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063858a135d14602d575b600080fd5b3360009081526007602052604090205460405190815260200160405180910390f3fea26469706673582212207dcd2251abcc0ec00a57991166abc6d399adfc8c51ab3763a0ed56717bbfa78264736f6c63430008140033";

type BankFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BankFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BankFacet__factory extends ContractFactory {
  constructor(...args: BankFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BankFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BankFacet__factory {
    return super.connect(runner) as BankFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BankFacetInterface {
    return new Interface(_abi) as BankFacetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BankFacet {
    return new Contract(address, _abi, runner) as unknown as BankFacet;
  }
}
