/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GemTokenChallengeFacet } from "./GemTokenChallengeFacet";
export type { IERC721Facet } from "./IERC721Facet";
