/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockedDiaSol from "./MockedDIA.sol";
export type { mockedDiaSol };
import type * as mockedUsdtSol from "./MockedUSDT.sol";
export type { mockedUsdtSol };
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { ERC721ReceiverMockCustomError } from "./ERC721ReceiverMockCustomError";
export type { ERC721ReceiverMockWithMessage } from "./ERC721ReceiverMockWithMessage";
export type { MockedERC721Enumerable } from "./MockedERC721Enumerable";
export type { MockedUSDC } from "./MockedUSDC";
