/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface LibERC20Interface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "ERC20Burned" | "ERC20Minted" | "ERC20Transferred"
  ): EventFragment;
}

export namespace ERC20BurnedEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, from: string, amount: bigint];
  export interface OutputObject {
    token: string;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20MintedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20TransferredEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    from: string,
    to: string,
    value: bigint
  ];
  export interface OutputObject {
    token: string;
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): LibERC20;
  waitForDeployment(): Promise<this>;

  interface: LibERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ERC20Burned"
  ): TypedContractEvent<
    ERC20BurnedEvent.InputTuple,
    ERC20BurnedEvent.OutputTuple,
    ERC20BurnedEvent.OutputObject
  >;
  getEvent(
    key: "ERC20Minted"
  ): TypedContractEvent<
    ERC20MintedEvent.InputTuple,
    ERC20MintedEvent.OutputTuple,
    ERC20MintedEvent.OutputObject
  >;
  getEvent(
    key: "ERC20Transferred"
  ): TypedContractEvent<
    ERC20TransferredEvent.InputTuple,
    ERC20TransferredEvent.OutputTuple,
    ERC20TransferredEvent.OutputObject
  >;

  filters: {
    "ERC20Burned(address,address,uint256)": TypedContractEvent<
      ERC20BurnedEvent.InputTuple,
      ERC20BurnedEvent.OutputTuple,
      ERC20BurnedEvent.OutputObject
    >;
    ERC20Burned: TypedContractEvent<
      ERC20BurnedEvent.InputTuple,
      ERC20BurnedEvent.OutputTuple,
      ERC20BurnedEvent.OutputObject
    >;

    "ERC20Minted(address,address,uint256)": TypedContractEvent<
      ERC20MintedEvent.InputTuple,
      ERC20MintedEvent.OutputTuple,
      ERC20MintedEvent.OutputObject
    >;
    ERC20Minted: TypedContractEvent<
      ERC20MintedEvent.InputTuple,
      ERC20MintedEvent.OutputTuple,
      ERC20MintedEvent.OutputObject
    >;

    "ERC20Transferred(address,address,address,uint256)": TypedContractEvent<
      ERC20TransferredEvent.InputTuple,
      ERC20TransferredEvent.OutputTuple,
      ERC20TransferredEvent.OutputObject
    >;
    ERC20Transferred: TypedContractEvent<
      ERC20TransferredEvent.InputTuple,
      ERC20TransferredEvent.OutputTuple,
      ERC20TransferredEvent.OutputObject
    >;
  };
}
