/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiamondERC721Facet } from "./IDiamondERC721Facet";
export type { SvbGemStones } from "./SvbGemStones";
