/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITargetContract__factory } from "./ITargetContract__factory";
export { MockedDAI__factory } from "./MockedDAI__factory";
