/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISaltVaultBulls } from "./ISaltVaultBulls";
export type { SaltVaultToken } from "./SaltVaultToken";
