/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as saltVaultTokenSol from "./SaltVaultToken.sol";
export type { saltVaultTokenSol };
export type { SVB_GemTokens } from "./SVB_GemTokens";
export type { SaltVaultBulls } from "./SaltVaultBulls";
