/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721Facet,
  IERC721FacetInterface,
} from "../../../../contracts/facets/GemTokenChallengeFacet.sol/IERC721Facet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721Facet__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721FacetInterface {
    return new Interface(_abi) as IERC721FacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721Facet {
    return new Contract(address, _abi, runner) as unknown as IERC721Facet;
  }
}
