/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISaltVaultBulls__factory } from "./ISaltVaultBulls__factory";
export { SaltVaultToken__factory } from "./SaltVaultToken__factory";
