/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BytesLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ERC721ReceiverMock,
  ERC721ReceiverMockInterface,
} from "../../../contracts/test/ERC721ReceiverMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "retval",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ERC721ReceiverMockRevert",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gas",
        type: "uint256",
      },
    ],
    name: "Received",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161031838038061031883398101604081905261002f9161004b565b6000805463ffffffff191660e09290921c91909117905561007c565b60006020828403121561005d57600080fd5b81516001600160e01b03198116811461007557600080fd5b9392505050565b61028d8061008b6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063150b7a0214610030575b600080fd5b61004361003e366004610103565b610060565b6040516001600160e01b0319909116815260200160405180910390f35b6000826033036100835760405163b58de7f160e01b815260040160405180910390fd5b7f28fa6e16458f9c24aa59ddd4085264573006dbe30304837873c7deafc702b038858585855a6040516100ba9594939291906101df565b60405180910390a15060005460e01b949350505050565b80356001600160a01b03811681146100e857600080fd5b919050565b634e487b7160e01b600052604160045260246000fd5b6000806000806080858703121561011957600080fd5b610122856100d1565b9350610130602086016100d1565b925060408501359150606085013567ffffffffffffffff8082111561015457600080fd5b818701915087601f83011261016857600080fd5b81358181111561017a5761017a6100ed565b604051601f8201601f19908116603f011681019083821181831017156101a2576101a26100ed565b816040528281528a60208487010111156101bb57600080fd5b82602086016020830137600060208483010152809550505050505092959194509250565b600060018060a01b03808816835260208188168185015286604085015260a06060850152855191508160a085015260005b8281101561022c5786810182015185820160c001528101610210565b5050600060c0828501015260c0601f19601f830116840101915050826080830152969550505050505056fea2646970667358221220b7ec67dcda7406b8aa317a46b4d3e3683768ea584f085eb705052a2aee680d0d64736f6c63430008140033";

type ERC721ReceiverMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC721ReceiverMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC721ReceiverMock__factory extends ContractFactory {
  constructor(...args: ERC721ReceiverMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    retval: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(retval, overrides || {});
  }
  override deploy(
    retval: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(retval, overrides || {}) as Promise<
      ERC721ReceiverMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC721ReceiverMock__factory {
    return super.connect(runner) as ERC721ReceiverMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC721ReceiverMockInterface {
    return new Interface(_abi) as ERC721ReceiverMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC721ReceiverMock {
    return new Contract(address, _abi, runner) as unknown as ERC721ReceiverMock;
  }
}
